---
   - name: capture show output
     hosts: ue5
     gather_facts: no
     connection: network_cli

     tasks:
       - name: show run
         ios_command:
           commands:
           - show run
           - show ip route
           - show version
         register: config

       - name: save output to local directory
         copy:
           content: "{{ config.stdout | replace('\\n', '\n') }}"
           dest: "/home/max/ansible/cisco/{{ inventory_hostname }}.ios"
