---

  - name: DEPLOY NEW SYSLOG SERVER ON HP3C SWITCH
    #hosts: Aruba 2930F-24G-4SFP
    hosts: all
    #gather_facts: no
    gather_facts: no
    #connection: local
    #become: true
    become_user: max
    #connection: network_cli
    connection: local
    #ansible_network_os: aruba
    #ansible_network_os: arubanetworks.aos_switch.arubaoss
    collections:
      - arubanetworks.aoscx
    vars:
    #  ansible_network_os: arubanetworks.aos_switch.arubaoss
      #ansible_network_os: arubanetworks.aoscx.aoscx
      ansible_network_os: aruba
      #ansible_python_interpreter: /home/max/.pyenv/shims/python3
      #ansible_network_cli_ssh_type: libssh
      #ssh_user: "{{ ansible_ssh_user }}"
      #ssh_pass: "{{ ansible_ssh_pass }}"

    tasks:

      #- name: adding new syslog server
      #  #arubanetworks.aos_switch.arubaoss_config:
      #  arubanetworks.aoscx.aoscx_config:
      #    #backup: true
      #    save_when: modified
      #    commands:
      #      - logging 137.204.25.235
      #    
      #- name: verify above command
      #  #community.network.aruba_command:
      #  #arubanetworks.aos_switch.arubaoss_command:
      #  arubanetworks.aoscx.aoscx_command:
      #    commands:
      #      - show syslog config
      #    wait_for:
      #      - result[0] contains 137.204.25.235
      #
      - name: adding new syslog server
        hp3c_config3:
          host: "{{ ansible_host }}"
          #the following is the system user and password, ie mng_reti
          ssh_user: "mng_reti"
          ssh_pass: "xxxxxxx"
          #ssh_user: "m.mattioli@unibo.it"
          #ssh_pass: "Gabri-2012"
          #ssh_user: "{{ ansible_ssh_user }}"
          #ssh_pass: "{{ ansible_ssh_pass }}"
          timeparam: 10
          commands:
            - info-center loghost 137.204.25.235 facility local1
            #- no ip ssh filetransfer
            #- tftp client
            #- copy tftp flash 137.204.22.33 E_11_43.swi primary
            #- show flash
            #- boot system flash primary
            #- write memory
          
          #tags: deploy