---
loop_protect:
  - A2-A8
  - B2-B8
  - C1-C24
  - D1-D24
  - E1-E24
  - F1-F24
  - G1-G24
  - H1-H24
  - I1-I24
  - J1-J24
  - K1-K24
  - L1-L24
  - Trk1
vlans:
    '1':
      id: '1'
      name: DEFAULT_VLAN
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 1/A2-1/A4,2/A1-2/A4,3/A2-3/A4
      vlan_voice: no voice
    '2103':
      id: '2103'
      name: VL_2103-VIDSORV
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2106':
      id: '2106'
      name: VL_2106-Telecont
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2109':
      id: '2109'
      #name: MANAGEMENT
      #ip_address: 172.30.28.22 255.255.255.0
      ports_tagged: Trk1
      ports_untagged: C1-C6,Trk1
      vlan_voice: no voice
    '2110':
      id: '2110'
      name: UTENZA_UFFICI
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 1/6-1/48,2/1-2/48,3/1-3/48
      vlan_voice: no voice
    '2111':
      id: '2111'
      name: VL_2111-VOIP
      ip_address: 'null'
      ports_tagged: 1/6-1/48,2/1-2/48,3/1-3/48,Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2112':
      id: '2112'
      name: UTENZA_SERVIZI_COMUNI
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2113':
      id: '2113'
      name: VL_2113-UE4-PRIV-LAB
      ip_address: 'null'
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice