---
ports:
  host_ports: A1-A8,B1-B8C1-C24D1-D24E1-E24F1-F24G1-G24H1-H24I1-I24J1-J24,K1-K24,L1-L24,Trk1
loop_protect:
  - A2-A8
  - B2-B8
  - C1-C24
  - D1-D24
  - E1-E24
  - F1-F24
  - G1-G24
  - H1-H24
  - I1-I24
  - J1-J24
  - K1-K24
  - L1-L24
ports_free:
  - A2-A8
  - B2-B8
  - C1-C24
  - D1-D24
  - E1-E24
  - F1-F24
  - G1-G24
  - H1-H24
  - I1-I24
  - J1-J24
  - K1-K24
  - L1-L24
vlans:
    '1':
      id: '1'
      name: DEFAULT_VLAN
      ports_tagged: Trk1
      ports_untagged: 1/A2-1/A4,2/A1-2/A4,3/A2-3/A4
      vlan_voice: no voice
    '2103':
      id: '2103'
      name: VL_2103-VIDSORV
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2106':
      id: '2106'
      name: VL_2106-Telecont
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice
    '2109':
      id: '2109'
      name: MANAGEMENT
      ports_tagged: Trk1
      ports_untagged: C1-C6,Trk1
      vlan_voice: no voice
    '2110':
      id: '2110'
      name: UTENZA_UFFICI
      ports_tagged: Trk1
      ports_untagged: 1/6-1/48,2/1-2/48,3/1-3/48
      vlan_voice: no voice
    '2111':
      id: '2111'
      name: VL_2111-VOIP
      ports_tagged: 1/6-1/48,2/1-2/48,3/1-3/48,Trk1
      ports_untagged: 'null'
      vlan_voice: voice
    '2113':
      id: '2113'
      name: VL_2113-UE4-PRIV-LAB
      ports_tagged: Trk1
      ports_untagged: 'null'
      vlan_voice: no voice