name: Ansible deploy

on:
  ## Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    #- name: Set up Python 3.7
    #  uses: actions/setup-python@v1
    #  with:
    #    python-version: 3.7
  
    - name: set ansible config secrets
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
       # DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
      run: |
        #touch /home/max/ansible/module/vault/.vault_pass
        echo "$ANSIBLE_VAULT_PASSWORD" > /home/max/ansible/module/vault/.vault_pass
        #mkdir .ssh
        #echo "$DO_SSH_KEY" > .ssh/id_digitalocean
        #chmod 666 /home/max/ansible/module/vault/.vault_pass
        
    - name: Run ansible script
      shell: bash 
      run: |
          cd /home/max/ansible/module
          ansible-playbook -i inventory.yml playbook/python.yml
